Repository eclipse/gemoc-studio, pull requests merged in 2018-06, with the labels that each got.

#80 Update Melange to version 2018-06-04
  pom.xml
Labels: bump

#88 Fixes eclipse help navigation table of content
  docs/org.eclipse.gemoc.studio.doc/src/main/asciidoc/dev/ContributingDocumentation.asciidoc
  docs/org.eclipse.gemoc.studio.doc/src/main/asciidoc/introduction_headContent.asciidoc
  gemoc_studio/plugins/org.eclipse.gemoc.language_workbench.documentation/plugin.xml
  gemoc_studio/plugins/org.eclipse.gemoc.language_workbench.documentation/toc.xml
Labels: documentation

#89 Fixes K3FSM example
  official_samples/K3FSM/docs/K3FSM.asciidoc
  official_samples/K3FSM/language_workbench/org.eclipse.gemoc.example.k3fsm.design/META-INF/MANIFEST.MF
  official_samples/K3FSM/language_workbench/org.eclipse.gemoc.example.k3fsm.design/description/k3fsm.odesign
  official_samples/K3FSM/language_workbench/org.eclipse.gemoc.example.k3fsm.design/src/org/eclipse/gemoc/example/k3fsm/design/services/FsmAnimatorServices.java
  official_samples/K3FSM/language_workbench/org.eclipse.gemoc.example.k3fsm.edit/META-INF/MANIFEST.MF
  official_samples/K3FSM/language_workbench/org.eclipse.gemoc.example.k3fsm.editor/META-INF/MANIFEST.MF
  official_samples/K3FSM/language_workbench/org.eclipse.gemoc.example.k3fsm.k3dsa/META-INF/MANIFEST.MF
  official_samples/K3FSM/language_workbench/org.eclipse.gemoc.example.k3fsm.xdsml/META-INF/MANIFEST.MF
  official_samples/K3FSM/language_workbench/org.eclipse.gemoc.example.k3fsm.xdsml/src-gen/.gitkeep
  official_samples/K3FSM/language_workbench/org.eclipse.gemoc.example.k3fsm.xtext.ide/META-INF/MANIFEST.MF
  official_samples/K3FSM/language_workbench/org.eclipse.gemoc.example.k3fsm.xtext.ui/META-INF/MANIFEST.MF
  official_samples/K3FSM/language_workbench/org.eclipse.gemoc.example.k3fsm.xtext/.launch/Launch Runtime Eclipse for K3FSM.launch
  official_samples/K3FSM/language_workbench/org.eclipse.gemoc.example.k3fsm.xtext/META-INF/MANIFEST.MF
  official_samples/K3FSM/language_workbench/org.eclipse.gemoc.example.k3fsm/src/.gitkeep
  official_samples/K3FSM/modeling_workbench/org.eclipse.gemoc.example.k3fsm.model_examples/.gitignore
  official_samples/K3FSM/modeling_workbench/org.eclipse.gemoc.example.k3fsm.model_examples/.launch/K3FSM - TwoStatesUpcast(abababa).launch
  official_samples/K3FSM/modeling_workbench/org.eclipse.gemoc.example.k3fsm.model_examples/.project
Labels: bug

#92 Show summary of checked out branches in multibranch pipeline
  Jenkinsfile
  dev_support/jenkins/showGitBranches.sh
Labels: releng

#69 Change start option for java9 and gtk3 support
  gemoc_studio/releng/org.eclipse.gemoc.gemoc_studio.product/gemoc_studio.product
Labels: bug

#96 Contact information update
  README.md
Labels: documentation
